# Generated by Django 4.1.5 on 2023-10-26 09:41

import Jobs.models
import Jobs.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Client_Name", models.CharField(max_length=100)),
                ("Date", models.DateField(default=datetime.date(2023, 10, 26))),
                (
                    "Delivery_Date",
                    models.DateField(default=Jobs.models.deliveryDay, max_length=150),
                ),
                (
                    "Material",
                    models.FileField(
                        blank=True,
                        upload_to="designs/%y",
                        validators=[Jobs.validators.file_size],
                    ),
                ),
                (
                    "Design",
                    models.FileField(
                        blank=True,
                        upload_to="designs/%y",
                        validators=[Jobs.validators.file_size],
                    ),
                ),
                (
                    "Shoulder_to_nipple_point",
                    models.CharField(default="0", max_length=100),
                ),
                (
                    "Shoulder_to_under_burst",
                    models.CharField(default="0", max_length=100),
                ),
                (
                    "Shoulder_to_half_length",
                    models.CharField(default="0", max_length=100),
                ),
                ("Shoulder_to_hip_part", models.CharField(default="0", max_length=100)),
                (
                    "Shoulder_to_knee_length",
                    models.CharField(default="0", max_length=100),
                ),
                (
                    "Shoulder_to_dress_length",
                    models.CharField(default="0", max_length=100),
                ),
                ("Burst", models.CharField(default="0", max_length=100)),
                ("Upper_burst", models.CharField(default="0", max_length=100)),
                ("Under_Burst", models.CharField(default="0", max_length=100)),
                (
                    "High_waist_measurement",
                    models.CharField(default="0", max_length=100),
                ),
                ("Waist_measurement", models.CharField(default="0", max_length=100)),
                ("High_hip", models.CharField(default="0", max_length=100)),
                ("Hip", models.CharField(default="0", max_length=100)),
                ("Knee_measurement", models.CharField(default="0", max_length=100)),
                ("Cleavage_level", models.CharField(default="0", max_length=100)),
                ("Shoulder_measurement", models.CharField(default="0", max_length=100)),
                ("Sleeve_length", models.CharField(default="0", max_length=100)),
                ("Round_sleeve_length", models.CharField(default="0", max_length=100)),
                ("Waist_to_hip", models.CharField(default="0", max_length=100)),
                ("Waist_to_knee", models.CharField(default="0", max_length=100)),
                ("Waist_to_floor", models.CharField(default="0", max_length=100)),
            ],
        ),
    ]
