# Generated by Django 4.1.5 on 2023-11-10 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="Backless",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="jobs",
            name="Round_Knee_For_Pant",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="jobs",
            name="Slit",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="jobs",
            name="Thigh",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="Date",
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
    ]
