# Generated by Django 4.1.5 on 2023-11-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0002_jobs_backless_jobs_round_knee_for_pant_jobs_slit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="Date",
            field=models.DateField(default=datetime.date(2023, 11, 14)),
        ),
    ]
