# Generated by Django 4.1.5 on 2023-11-14 17:46

import Staffs.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaSt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ROLE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SEX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Surname", models.CharField(max_length=100)),
                ("Firstname", models.CharField(max_length=100)),
                ("Other", models.CharField(blank=True, max_length=100)),
                (
                    "Date_of_Birth",
                    models.DateField(default=datetime.date(2023, 11, 14)),
                ),
                ("State_of_Origin", models.CharField(max_length=1000)),
                ("LGA", models.CharField(max_length=100)),
                ("Religion", models.CharField(max_length=1000)),
                ("Home_Address", models.CharField(max_length=1000)),
                ("Phone_Number", models.CharField(max_length=1000)),
                ("Next_Of_Kin", models.CharField(max_length=1000)),
                ("Relationship", models.CharField(max_length=1000)),
                ("NOK_Phone", models.CharField(max_length=1000)),
                ("NOK_Email_Adress", models.CharField(max_length=1000)),
                (
                    "Marital_Status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Staffs.mast",
                    ),
                ),
                (
                    "Sex",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Staffs.sex",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BioData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Surname", models.CharField(max_length=100)),
                ("Firstname", models.CharField(max_length=100)),
                ("Other", models.CharField(blank=True, max_length=100)),
                (
                    "Date_of_Birth",
                    models.DateField(default=datetime.date(2023, 11, 14)),
                ),
                ("State_of_Origin", models.CharField(max_length=1000)),
                ("LGA", models.CharField(max_length=100)),
                ("Religion", models.CharField(max_length=1000)),
                ("Home_Address", models.CharField(max_length=1000)),
                ("Phone_Number", models.CharField(max_length=1000)),
                ("Next_Of_Kin", models.CharField(max_length=1000)),
                ("Relationship", models.CharField(max_length=1000)),
                ("NOK_Phone", models.CharField(max_length=1000)),
                ("Email_Adress", models.CharField(max_length=1000)),
                (
                    "Marital_Status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Staffs.mast",
                    ),
                ),
                (
                    "Sex",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Staffs.sex",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                (
                    "Passport",
                    models.FileField(
                        blank=True,
                        upload_to="Passports/%y",
                        validators=[Staffs.validators.file_size],
                    ),
                ),
                ("Date", models.DateField(default=datetime.date(2023, 11, 14))),
                ("Working_Hours", models.CharField(max_length=100)),
                ("Break_Time", models.CharField(max_length=100)),
                ("Closing_Hours", models.CharField(max_length=100)),
                ("To_Produce", models.CharField(max_length=100)),
                ("Salary", models.CharField(max_length=1000)),
                ("Work_Duration", models.CharField(max_length=100)),
                ("Terms_And_Conditions", models.BooleanField()),
                (
                    "Job_Role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Staffs.role",
                    ),
                ),
            ],
        ),
    ]
