# Generated by Django 4.1.5 on 2023-11-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventories", "0002_alter_items_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="update_Date",
            field=models.DateField(default=datetime.date(2023, 11, 14), null=True),
        ),
    ]
