# Generated by Django 4.1.5 on 2023-10-26 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10000)),
                ("Account_Number", models.CharField(max_length=10000)),
                ("Bank", models.CharField(max_length=1000)),
                ("Swift_Code", models.CharField(max_length=1000)),
                ("Mail", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="CUR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Customer_Name",
                    models.CharField(default="non", max_length=1000, null=True),
                ),
                ("Order_Date", models.DateField(default=datetime.date(2023, 10, 26))),
                (
                    "Due_Date",
                    models.CharField(default="non", max_length=1000, null=True),
                ),
                ("Phone", models.CharField(default="non", max_length=1000, null=True)),
                ("AW", models.CharField(default="non", max_length=1000, null=True)),
                ("Orders", models.CharField(default="non", max_length=1000, null=True)),
                ("Count", models.CharField(default="non", max_length=1000, null=True)),
                ("Amount", models.CharField(max_length=1000)),
                ("Shipping", models.CharField(max_length=1000)),
                (
                    "Subtotal",
                    models.CharField(default="non", max_length=100, null=True),
                ),
                ("NameId", models.CharField(default="non", max_length=1000, null=True)),
                ("VAT", models.CharField(default="non", max_length=1000, null=True)),
                ("Total", models.CharField(default="non", max_length=1000, null=True)),
                (
                    "Curency",
                    models.ForeignKey(
                        default="USD",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Invoice.cur",
                    ),
                ),
            ],
        ),
    ]
