# Generated by Django 4.1.5 on 2023-11-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0002_alter_invoice_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="Order_Date",
            field=models.DateField(default=datetime.date(2023, 11, 14)),
        ),
    ]
